---
- name: restart carbonapi
  service:
    name: carbonapi
    state: started
    enabled: true
  become: true
- name: restart carbonzipper 
  service: 
    name: carbonzipper
    state: restarted
    enabled: true
  become: true
