---
- name: copy grafana deb 
  copy:
    src: "{{ deb_file_name }}"
    dest: /tmp/grafana.deb
  become: true
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") 
- name: install grafana
  apt:
    deb: /tmp/grafana.deb
  become: true
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") 
- name: grafana config 
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana
  become: true
- name: cleanup
  file:
    path: /tmp/grafana.deb
    state: absent
  become: true 
  
