---
- name: Upload debfile
  copy:
    src: "{{ deb_source_file }}"
    dest: /tmp/carbonapi.deb
  become: true

- name: copy carbonzipper
  copy:
    src: "{{ carbonzipper_deb }}"
    dest: /tmp/carbonzipper.deb
  become: true

- name: install debfiles
  apt:
    deb: "{{ item }}"
  with_items: 
    - /tmp/carbonapi.deb
    - /tmp/carbonzipper.deb
  become: true
  notify: restart carbonzipper
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: install memcached
  apt:
    name: memcached
    state: present
  become: true
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: create defaults file
  copy:
    src: carbonapi
    dest: /etc/default/carbonapi
  become: true
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: create config folder
  file:
    path: /etc/carbonapi
    owner: root
    group: root
    mode: 0755
    state: directory
  become: true

- name: create config file
  template:
    src: "{{ carbonapi_conf_template }}"
    dest: /etc/carbonapi/carbonapi.yaml
  become: true
  notify: restart carbonapi
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: cleanup
  file:
    path: {{ item }}
    state: absent
  become: true
  with_items:
    - /tmp/carbonapi.deb
    - /tmp/carbonzipper.deb
